// Login
export const ACTION_LOGIN = 'ACTION_LOGIN';
export const ACTION_FAILED = 'ACTION_FAILED';
// ReceiveRepair
export const JSON_FEED_FETCHING = 'JSON_FEED_FETCHING';
export const JSON_FEED_SUCCESS = 'JSON_FEED_SUCCESS';
export const JSON_FEED_FAILED = 'JSON_FEED_FAILED';
export const ACTION_RECIVER_JOB_SELECT = 'ACTION_RECIVER_JOB_SELECT';
export const ACTION_RECIVER_JOB_SUCCESS = 'ACTION_RECIVER_JOB_SUCCESS';
export const ACTION_RECIVER_JOB_FAILED = 'ACTION_RECIVER_JOB_FAILED';
export const ACTION_RECEIVEREPAIR_DETAIL_SUCCESS =
  'ACTION_RECEIVEREPAIR_DETAIL_SUCCESS';
export const ACTION_RECEIVEREPAIR_DETAIL_FAILED =
  'ACTION_RECEIVEREPAIR_DETAIL_FAILED';
export const ACTION_RECEIVEREPAIR_CREATE_REPAIR_WORK_SUCCESS =
  'ACTION_RECEIVEREPAIR_CREATE_REPAIR_WORK_SUCCESS';
export const ACTION_RECEIVEREPAIR_CREATE_REPAIR_WORK_FAILED =
  'ACTION_RECEIVEREPAIR_CREATE_REPAIR_WORK_FAILED';
export const ACTION_REJECT_SUCCESS = 'ACTION_REJECT_SUCCESS';
export const ACTION_REJECT_FAILED = 'ACTION_REJECT_FAILED';
export const ACTION_LIST_PIKCER = 'ACTION_LIST_PIKCER';
export const ACTION_GET_SIZE_OF_PIPES = 'ACTION_GET_SIZE_OF_PIPES';
export const ACTION_GET_REQUEST_CATEGORY = 'ACTION_GET_REQUEST_CATAGORY';
export const ACTION_GET_INCIDENT_REJECT_TYPE_SUCCESS =
  'ACTION_GET_INCIDENT_REJECT_TYPE_SUCCESS';
export const ACTION_GET_INCIDENT_REJECT_TYPE_FAILED =
  'ACTION_GET_INCIDENT_REJECT_TYPE_FAILED';

//WorkRepair
export const ACTION_JSON_WORKREPAIR_FETCHING =
  'ACTION_JSON_WORKREPAIR_FETCHING';
export const ACTION_JSON_WORKREPAIR_SUCCESS = 'ACTION_JSON_WORKREPAIR_SUCCESS';
export const ACTION_JSON_WORKREPAIR_FAILED = 'ACTION_JSON_WORKREPAIR_FAILED';
export const ACTION_GETREPAIRWORKBYID_SUCCESS =
  'ACTION_GETREPAIRWORKBYID_SUCCESS';
export const ACTION_GETREPAIRWORKBYID_FAILED =
  'ACTION_GETREPAIRWORKBYID_FAILED';
export const ACTION_PHOTO = 'ACTION_PHOTO';
export const ACTION_PHOTO_RESET = 'ACTION_PHOTO_RESET';
export const ACTION_RADIO_PIPE = 'ACTION_RADIO_PIPE';

// Title
export const ACTION_TITLE_NO = 'ACTION_TITLE_NO';

// Profile
export const ACTION_PROFILE_TARGET = 'ACTION_PROFILE_TARGET';
export const ACTION_GET_NUM_OF_WORK_SUCCESS = 'ACTION_GET_NUM_OF_WORK_SUCCESS';
export const ACTION_GET_NUM_OF_WORK_FAILED = 'ACTION_GET_NUM_OF_WORK_FAILED';

// jobsurvey
export const ACTION_WORKSURVEY_TARGET_IMAGE = 'ACTION_WORKSURVEY_TARGET_IMAGE';
export const ACTION_UPDATE_REPAIR_WORK_SUCCESS =
  'ACTION_UPDATE_REPAIR_WORK_SUCCESS';
export const ACTION_UPDATE_REPAIR_WORK_FAILED =
  'ACTION_UPDATE_REPAIR_WORK_FAILED';
export const ACTION_UPDATE_REPAIRWORK_PROCESS =
  'ACTION_UPDATE_REPAIRWORK_PROCESS';
export const ACTION_UPDATE_REPAIRWORK_CLOSEJOB =
  'ACTION_UPDATE_REPAIRWORK_CLOSEJOB';

// RepairFilter
export const ACTION_GET_INCIDENT_SEARCH_SUCCESS =
  'ACTION_GET_INCIDENT_SEARCH_SUCCESS';
export const ACTION_GET_INCIDENT_SEARCH_FAILED =
  'ACTION_GET_INCIDENT_SEARCH_FAILED';
export const ACTION_SET_SEARCH_PARAMS = 'ACTION_SET_SEARCH_PARAMS';
export const ACTION_SET_WORK_REPAIR_SEARCH_PARAMS = 'ACTION_SET_WORK_REPAIR_SEARCH_PARAMS';
export const ACTION_RESET_RECEIVE_REPAIR = 'ACTION_RESET_RECEIVE_REPAIR';
export const ACTION_RESET_WORK_REPAIR = 'ACTION_RESET_WORK_REPAIR';
export const ACTION_RESET_REPAIR_FILTER = 'ACTION_RESET_REPAIR_FILTER';

//  SaveLocationPointNormal
export const ACTION_SAVE_LOCATION_POINT_NORMAL_SUCCESS =
  'ACTION_SAVE_LOCATION_POINT_NORMAL_SUCCESS';
export const ACTION_SAVE_LOCATION_POINT_NORMAL_FAILED =
  'ACTION_SAVE_LOCATION_POINT_NORMAL_FAILED';

// Remem
export const ACTION_REMEM_WORKCARRYREPAIR = 'ACTION_REMEM_WORKCARRYREPAIR';